services:
  dns-update:
    image: ghcr.io/davide-88/dns-update:release
    container_name: dns-update
    env_file:
      - .env
    volumes:
      - ./volumes/log:/var/log
networks:
  default:
    driver: bridge
